# Generated by Django 3.2.20 on 2023-10-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
